### ISSUE TITLE
How to run in headless mode?

### ISSUE THREAD

**Issue by BlackHole1** [muralikg/puppetcam#10]
I want to put it in the docker, but in headless mode, it won't work. Is there any good way?

**Comment by muralikg** [comment]
There are [docker images with xvfb ](https://github.com/auth0/docker-xvfb)running inside them which should help you automate the process. Though I have not tested with those images, it should be similar to running it on ubuntu as I had tested.

The approach shown in the example will not run in headless mode, hence the use of xvfb.

**Comment by BlackHole1** [comment]
This is great, thank you very much.
