### ISSUE TITLE
Ability to record higher quality videos

### ISSUE THREAD

**Issue by abhishekgahlot** [muralikg/puppetcam#11]
Hi,

Your repo is amazing and works well in Mac, Is it possible to record higher quality videos like 1080p. Currently its recording 720p. 

Thanks

**Comment by muralikg** [comment]
@abhishekgahlot  have you tried changing bit rate in `background.js`.
This `videoBitsPerSecond` property will let you adjust quality of the output file.

**Comment by muralikg** [comment]
Also the height of the browser and captured viewport is hardcoded to 720 pixels (in export.js and background.js). Try tweaking them and simultaneously increasing bitrate for higher quality videos.

Some [references](https://stackoverflow.com/questions/27420581/get-maximum-video-resolution-with-getusermedia)
```
var constraints = { 
    video: {
        width: { ideal: 4096 },
        height: { ideal: 2160 } 
    } 
};
```

**Comment by abhishekgahlot** [comment]
Thanks @muralikg, Yup before i saw your comment I tried that and it worked :-)

**Comment by abhishekgahlot** [comment]
I am closing the issue @muralikg , Thanks for your help!

**Comment by Insayt** [comment]
@muralikg please can show an example how to make 1080p 60fps?

export.js
 ```
var width       = 1920;
var height      = 1080;
```

background.js
```
minWidth: 1920,
maxWidth: 1920,
minHeight: 1080,
maxHeight: 1080,
```

```
recorder = new MediaRecorder(stream, {
                videoBitsPerSecond: 15728640,
                ignoreMutedMedia: true,
                mimeType: 'video/webm'
            });
```
https://www.youtube.com/watch?v=IizSh-XYMYA&feature=youtu.be
does not work :(

but by default 720p 60ps works
https://www.youtube.com/watch?v=_q1dWKGGvic

**Comment by muralikg** [comment]
I have not done it myself. @abhishekgahlot can you please share your example here so that others can benefit from your work.

**Comment by abhishekgahlot** [comment]
@muralikg @Insayt I was AFK yesterday I think I was making 50fps video with current code.

@Insayt Can you tell me how much you are currently able to make and which OS or Xvfb version are you using?

```
navigator.webkitGetUserMedia({
            audio: false,
            video: {
              mandatory: {
                chromeMediaSource: 'desktop',
                chromeMediaSourceId: streamId,
                minWidth: 1920,
                maxWidth: 1920,
                minHeight: 1080 ,
                maxHeight: 1080,
                minFrameRate: 60,
              }
            }
          }
```

Here is my code snippet I am using.

**Comment by abhishekgahlot** [comment]
@Insayt Also here i do see 1080p option here: https://www.youtube.com/watch?v=IizSh-XYMYA&feature=youtu.be

**Comment by Insayt** [comment]
@abhishekgahlot I could not do 60 fps :(

**Comment by Insayt** [comment]
The problem was in xvfb :)

**Comment by abhishekgahlot** [comment]
Great @Insayt, Glat that worked out for you!

**Comment by somprabhsharma** [comment]
@Insayt What was the problem in xvfb and how did you fix it? I am also unable to record video on 60fps.
