### ISSUE TITLE
Mp4 video format

### ISSUE THREAD

**Issue by jsilvia721** [muralikg/puppetcam#12]
Does this support mp4 video files? I've changed the MIME type to `video/mp4` along with the Blob type but it seems like the video never finishes downloading. Does MediaRecorder not support this MIME type?

**Comment by muralikg** [comment]
@jsilvia721  these are the mime types supported by chrome `MediaRecorder` API.
https://stackoverflow.com/questions/41739837/all-mime-types-supported-by-mediarecorder-in-firefox-and-chrome.

Looks like Chrome doesn't support that mime type
```js
MediaRecorder.isTypeSupported('video/mp4;codecs=h264')
# false
```
