### ISSUE TITLE
can I record video of more than one tabs at the same time?

### ISSUE THREAD

**Issue by MJunaidAhmad** [muralikg/puppetcam#13]
First of all amazing work!
I wanted to convert your code to an API. So users will provide me a URL and time and I will record that web page for specified time and will give the video to users. I just want to confirm that multiple requests will work fine? it would be creating new tabs and record video separately every time a user sends a request?
I know its a silly question but just wanted to confirm. :p 

Regards,
Junaid

**Comment by muralikg** [comment]
I am avoiding user permission dialog by setting this command line flag for chrome `--auto-select-desktop-capture-source=puppetcam` which should match the tab title. So only one tab can be captured at a time. 
I haven't come across other ways of bypassing the user consent dialog box.

You may have to run multiple instances of chrome to handle multiple URLs

**Comment by MJunaidAhmad** [comment]
Thanks you so much for the reply. And yes you are right. Running multiple instances of chrome solved the problem. Thanks again. :)
