### ISSUE TITLE
Recording video of an unknown URL

### ISSUE THREAD

**Issue by MJunaidAhmad** [muralikg/puppetcam#14]
Sometimes its recording video of this URL: http://www.bellygraph.com/

The original URL that I am trying to make video is: http://prezentar.net:81/player/50825

Doesn't give any exception either.

Any thoughts?
Do I need to show you my code?

Thanks in advance!

**Comment by muralikg** [comment]
Are there multiple tabs and one of the tab has the other URL. Note this example will only work with a single tab.

**Comment by MJunaidAhmad** [comment]
No there are no multiple tabs but there are multiple browsers open at the same time. As I am opening new browser for every new request. Let's say I receive 10 requests then I will open 10 browsers and it will randomly create some dummy video (and some of them giving error on opening => invalid media).
It might be due to the GLOBAL Chrome, MediaRecorder and FileReader variables in the backgorund.js? Because once I sent 20 request and it started giving me warning "MaxListenersExceedingWarning" due to eventemitter memory leak...

**Comment by MJunaidAhmad** [comment]
okay I tried to debug it and printed the page URL after this line: (export.js) 
`const page = pages[0]`

like this: 
`console.log(page.url());`

Sometimes it prints ":" and sometimes "about:blank".

In the first case it is always making video with the right content. But in second rarely its making right video. 
I don't know why its happening.

**Comment by MJunaidAhmad** [comment]
Also, the video duration is random. I am trying to make video of 60 seconds but its capturing only 32 seconds video. Do you have any idea why its happening?

**Comment by muralikg** [comment]
I have not tried with multiple instances of chrome in parallel and the issues you face could very well be because of that. Do you get the same issues when you run a single instance?

**Comment by MJunaidAhmad** [comment]
Yes, I have ran all these tests on single instance of chrome and getting the same errors.

**Comment by muralikg** [comment]
I dont see anything wrong when I try that same URL. I would suggest you disable xvfb and try to open chrome with GUI. Then go to chrome extensions enable developer mode and check if there are errors in background.js

**Comment by muralikg** [comment]
@MJunaidAhmad  Can you post your code, I will take a look at it.

**Comment by MJunaidAhmad** [comment]
That was a server specific bug. We changed our servers and its working fine. May there was some kind of ad virus on server.

Thanks!
