### ISSUE TITLE
Can I use Puppetcam to screencast a Google Meet conference and then pipe it to FFMPEG?

### ISSUE THREAD

**Issue by jzvi12** [muralikg/puppetcam#20]
Is this possible to do in a headless Ubuntu server considering google Authentication?
Does Puppetcam only save files in .webm format? Can I use .mp4 instead?
Any thoughts on how to accomplish this?

**Comment by muralikg** [comment]
You can refer to this issue to know about formats supported by Chrome [https://github.com/muralikg/puppetcam/issues/12](https://github.com/muralikg/puppetcam/issues/12)

Have not tried exporting a google meet or anything involving google authentication. But I dont see any reason why you cannot do that unless google blocks requests if they detect automation.
