### ISSUE TITLE
trouble running on WSL

### ISSUE THREAD

**Issue by danisharora099** [muralikg/puppetcam#25]
chromium won't run on WSL & Xvfb won't run on Windows; why is headless: false? wouldnt running on a server require headless: true?

**Comment by shubham-pixelnx** [comment]
What's your usecase?

**Comment by danisharora099** [comment]
@shubham-pixelnx I'm wanting to spawn a chromium instance, go to our meeting URL, record that meeting, and save it to the server. All of it needs to happen on our EC2 instance

**Comment by shubham-pixelnx** [comment]
@danisharora099 I've also tried the same but the framerate won't be good enough for such cases. The output will be jerky.

**Comment by danisharora099** [comment]
Got it - gonna resort to server-side recording & post-processing then

**Comment by shubham-pixelnx** [comment]
Didn't get you, what are you planning instead?

**Comment by danisharora099** [comment]
Recording individual RTP streams (diverting them from the media router to a new endpoint on ffmpeg/Gstreamer, and recording them). Once those individual streams have been recorded, using ffmpeg/Gstreamer again to assemble those A/V streams into one single file.

Note: this is only possible because I control my media router (backend).

**Comment by shubham-pixelnx** [comment]
Getting a bit, So do you've full control over those meeting links, to put custom code there, and so on the frontend as well?
