### ISSUE TITLE
should audio recording work?

### ISSUE THREAD

**Issue by brandonmp** [muralikg/puppetcam#4]
Thanks for putting this together.

I'm trying to record video w/ audio. Out of the box this doesn't seem to work (on Ubuntu)--is it something you've looked into?

**Comment by brandonmp** [comment]
yeah I gave that a shot. it doesn't fail outright, but the program doesn't stop after the timeout when `audio: true`. 

thanks for the quick response--will keep at it & update for posterity if I find something

**Comment by steinex** [comment]
@brandonmp did you find a workaround for the issue that the timeout doesn't work with `audio: true`?

**Comment by bitk0der** [comment]
Audio recording works well, insted `audio: true` you should use:
```
audio: {
                  mandatory: {
                      chromeMediaSource: 'system'
                  }
}
```

**Comment by muralikg** [comment]
@brandonmp,
I have tested @bitk0der 's solution and it works well. Feel free to open the issue if needed.

**Comment by FisherRobison** [comment]
Any ideas on getting audio to work in docker? This fork (https://github.com/pzagor2/puppetcam) works awesome for docker but having issues with audio.  @pzagor2

**Comment by pzagor2** [comment]
@FisherRobison I haven't spend any time trying to get the audio to work.

**Comment by muralikg** [comment]
@FisherRobison  Have you tried [this](https://github.com/jessfraz/dockerfiles/issues/85#issuecomment-299431931)?
Looks like you need to map some devices from host machine to the container

**Comment by zakcali** [comment]
> Audio recording works well, insted `audio: true` you should use:
> 
> ```
> audio: {
>                   mandatory: {
>                       chromeMediaSource: 'system'
>                   }
> }
> ```

Unfortunately, audio is not recording in Windows 10. 
I could only able to full screen (not chrome tab) capture with audio included in Windows 10.
Reference:
https://www.electronjs.org/docs/api/desktop-capturer
