### ISSUE TITLE
Changing download folder?

### ISSUE THREAD

**Issue by theianjohnson** [muralikg/puppetcam#6]
I'm currently working through the docs to try and find this as well, but have you seen any way to change the download location? Ideally I'd like to just download the video into a subdirectory relative to where the script is being run from, ie - 

```
/puppetcam
    export.js
    ... etc
    /videos
        spinner.webm <- can we get it here?
```

Currently it gets dropped into the `~/Downloads/spinner.webm` folder on my virtual machine, then I have to manually move to a linked folder to access (using Vagrant and Virtualbox with a *nix image)

I tried with a relative path as a filename, but no luck, still dropped it in `~/Downloads`

**Comment by muralikg** [comment]
You can only set relative paths from the download location as per the [docs](https://developer.chrome.com/extensions/downloads#method-download). To set a custom downloads folder you need to create a chrome profile with that appropriate location and use that with puppeteer. I thought it is easier to `mv` the file through a script than go through that hassle

**Comment by theianjohnson** [comment]
Looks like that is indeed the best way to go, for any future readers, my solution using `fs`

```
fs.copyFile('/home/vagrant/Downloads/'+ exportname, __dirname +'/screencasts/'+ exportname, (err) => {if(err) console.log(err)});
fs.unlink('/home/vagrant/Downloads/'+ exportname, (err) => {if(err) console.log(err)});
```

I couldn't just do fs.rename since moving from a non-vagrant synced folder to a synced folder is across partitions
